
abstract: ~
author: Sal Zhong (Zhong Wei Xiang)
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.55
license: perl
name: Xul2ppt_mec
no_index: 
  directory: 
    - inc
    - t
requires: 
  Clipboard: 0
  Win32::GuiTest: 0
version: 0.01
